#version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql   #docker-compose down -v

  auth-service:
    build: ./auth-service
    ports:
    - "3001:3001" # Agrega esta línea para mapear el puerto
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

  product-service:
    build: ./product-service
    ports:
    - "3002:3002" # Agrega esta línea para mapear el puerto
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service

volumes:
  postgres_data: